config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'cart', to: 'cart#show'
  root 'pages#home'
  resources :foods
  devise_for :users
  get 'menu', to: "pages#menu"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect {|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0}.sum
  end
  
  private
  def set_subtotal
    self[:subtotal] = subtotal
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # if there is a record
    if persisted?
      self[:unit_price]
    else
      food.price
    end
  end

  def total
    return unit_price * quantity
  end
  
  private
  def set_unit_price
    self[:unit_price] = unit_price
  end
  
  def set_total
    self[:total] = total * quantity
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :description, :price)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order
 
  def create
    @order_item = @order.order_items.new(order_params)
    @order.save
    
    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private 
  def order_params
    params.require(:order_item).permit(:foods_id, :quantity)
  end
  
  def set_order
    @order = current_order
  end
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def menu
    @foods = Food.all
    @order_item = current_order.order_items.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    # Use Find by id to avoid potential errors
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with value of Rp.#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
  <h3><%= item.food.name %></h3>
  <h3><%= item.food.price %></h3>
  <%= form_with model: item do |f| %>
    <%= f.hidden_field :food_id, value: item.food.id %>
    <%= f.number_field :quantity, value: item.quantity.to_i %>
    <%= f.submit "Update Cart" %>
    <%= button_to "Remove Items", item, method: :delete %>
  <% end %>
  <h2>Subtotal : <%= item.total %></h2>
<% end %>
<h3>Your current order has a total of: <%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
  <%= render "cart_items" %>
</div>
<hr>

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= food.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foods</h1>

<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <p>
      <%= link_to "Show this food", food %>
    </p>
  <% end %>
</div>

<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Food Family Catering</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Menu", menu_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Welcome, <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= button_to "Logout", destroy_user_session_path,class:'dropdown-item', method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "sign in", new_user_session_path, class: "nav-link  text-capitalize" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodFamCatering</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container p-4">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/order_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");

app/views/order_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/order_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/menu.html.erb
<div class="menu-container">
  <div class="row">
    <% @foods.each do |food|%>
      <div class="col-4">
        <h5><%= food.name %></h5>
        <p><%= food.description %></p>
        <span><%= food.price %></span>
        <%= form_with model: @order_item, local: false do |f| %>
          <%= f.hidden_field :foods_id, value: food.id %>
          <%= f.number_field :quantity, value: 1, min: 1 %>
          <%= f.submit "Add to Cart" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>